/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: DYY                                                   *
* Dimensions:  64 * 64                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmDYY;

#if 0


/*********************************************************************
*
*  This palette is included for reference only
*  As it is saved as device dependent bitmap without color info.
*  Please note that this bitmap requires the physical palette to be
*  identical to the palette of the display.
*  If this does not work out, please convert your bitmap into a DIB 
*/
/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _ColorsDYY[] = {
  0x000000, 0xFFFFFF
};

#endif

static GUI_CONST_STORAGE GUI_LOGPALETTE _PalDYY = {
  2,  // Number of entries
  0,  // No transparency
  NULL
};

static GUI_CONST_STORAGE unsigned char _acDYY[] = {
  ________, ________, ________, ________, X_______, ________, ________, ________,
  ________, ________, ________, ____XXXX, XX_XXXXX, X_______, ________, ________,
  ________, ________, _______X, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________,
  ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________,
  ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  ________, ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________,
  ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________,
  ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________,
  ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________,
  ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________,
  ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________,
  ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________,
  ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________,
  ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________,
  ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX__XXX, XXXX____, ________,
  ________, ________, XXXXXXXX, XXXXXXXX, XXXXXXX_, _XX__XXX, XXXX____, ________,
  ________, ________, XXXXXXXX, XXXXXXXX, XX_XXX__, _X___XXX, XXXXX___, ________,
  ________, ________, XXXXXXX_, ___XXXX_, ______XX, XXXXXXXX, XXX_X___, ________,
  ________, ________, XXXXXX__, __XXXX__, _____XX_, _X___XXX, XXXXX___, ________,
  ________, ________, XXXXXX__, _____X__, __XXXX__, _X___XX_, XXXXX___, ________,
  ________, ________, XXX_X___, ___XX___, __XX____, XX____X_, _XXX____, ________,
  ________, ________, XXXXX___, ____XXX_, __X___XX, _______X, _XXX____, ________,
  ________, ________, XXXX_XXX, XX__X_XX, ______X_, __XXXX_X, _XXX____, ________,
  ________, ________, XXXX____, __XXX__X, X___X___, _XXXX__X, _XXX____, ________,
  ________, ________, XXXX____, _XX_____, __XXX_XX, XXXXX___, XXXX____, ________,
  ________, ________, XXXX____, XXXXXX__, _X___XXX, XXX_____, XXXX____, ________,
  ________, ________, XXXX_X__, __XXXXX_, _X__X___, __X_____, _XX_____, ________,
  ________, ________, XXXX_XXX, ____XXX_, _XX__X__, __XXX___, _XX_____, ________,
  ________, ________, XXXX___X, XXXXXXX_, _XX__XXX, XXXXXX__, _XX_____, ________,
  ________, ________, XXXX____, XXXXXXX_, _XX___XX, XXXXX___, _XX_____, ________,
  ________, ________, XXXX___X, ________, _XX_____, _______X, _XX_____, ________,
  ________, ________, XXXX__X_, ________, _XX_____, _______X, _XX_____, ________,
  ________, ________, _X__X_X_, ________, _XX___XX, _______X, XXX_____, ________,
  ________, ________, _XXX_X__, ________, _XX___XX, ___X___X, XXX_____, ________,
  ________, ________, _XXX_X__, ________, _XX___XX, ___X___X, XX______, ________,
  ________, ________, __XXXX__, ___X_XX_, _XX___X_, ___X___X, XX______, ________,
  ________, ________, __XXX___, ___XXXX_, _XX___X_, ___X___X, X_______, ________,
  ________, ________, ___XX___, ___X_XXX, _XX_XXXX, X______X, X_______, ________,
  ________, ________, ___XX___, ___X__XX, XXXXXX__, X______X, X_______, ________,
  ________, ________, ___XX___, ___X___X, XXXXXX__, X______X, X_______, ________,
  ________, ________, ___XXX__, ____X___, XXXXX___, X_____XX, ________, ________,
  ________, ________, ___XXX__, ___X_XX_, XXXXXX_X, X_____XX, ________, ________,
  ________, ________, ____XX__, _XXX____, XXX_____, ______XX, ________, ________,
  ________, ________, ____XX__, XX______, ________, ______XX, ________, ________,
  ________, ________, ____XXX_, ________, ________, ______XX, ________, ________,
  ________, ________, ____XXX_, _____XXX, XXX__XX_, ______XX, ________, ________,
  ________, ________, ________, ___XXXX_, __X___XX, _____XXX, ________, ________,
  ________, ________, ____XX__, __XXX___, _______X, _____XX_, ________, ________,
  ________, ________, ___XX___, __XXXXX_, _XX__XXX, _____XX_, ________, ________,
  ________, ________, _XXX____, _XX_____, __X_____, ____XXX_, ________, ________,
  ________, _______X, XXXXX___, ________, __X_____, ____XXX_, ________, ________,
  ________, ___XXXXX, XXXXX___, ________, ___X____, ____XXXX, ________, ________,
  ________, XXXXXXXX, XXXXXX__, ________, ___X____, ___XXXXX, XXX_____, ________,
  ______XX, XXXXXXXX, XXXXXX__, ____X___, _XXX____, ___XXXXX, XXXXX___, ________,
  _____XXX, XXXXXXXX, XXXXXX__, ___XX___, _XX_____, __XXXXXX, XXXXXXX_, ________,
  ___XXXXX, XXXXXXXX, XXXX_X__, ___X____, _X______, __XXXXXX, XXXXXXXX, XX______,
  __XXXXXX, XXXXXXXX, XXXX____, ___XX___, _X______, __XXXXXX, XXXXXXXX, XXXX____,
  _XXXXXXX, XXXXXXXX, XXXXX___, _____X__, _X______, __XXXXXX, XXXXXXXX, XXXXX___,
  XXXXXXXX, XXXXXXXX, XXXXX___, ________, _XX_____, __XXXXXX, XXXXXXXX, XXXXXX__,
  _XXXXXXX, XXXXXXXX, XXXXX___, ________, __X_____, _XXXXXXX, XXXXXXXX, XXXXXX__,
  __X_XXXX, XXXXX_XX, XXXX____, ________, __X_____, _X__XXXX, XX_XX_XX, XXXXXXX_
};

GUI_CONST_STORAGE GUI_BITMAP bmDYY = {
  64, // xSize
  64, // ySize
  8, // BytesPerLine
  1, // BitsPerPixel
  _acDYY,  // Pointer to picture data (indices)
  &_PalDYY   // Pointer to palette
};

/*************************** End of file ****************************/
